### ISSUE TITLE
How to execute the project

### ISSUE THREAD

**Issue by robinnidhi** [wolverdude/GenSON#2]
I have downloaded the project into eclipse and tried to run but getting errors

Traceback (most recent call last):
  File "C:\Users\rabindra\git\GenSON\test\test_bin.py", line 68, in <module>
    unittest.main()
  File "C:\Program Files\Python32\lib\unittest\main.py", line 123, in __init__
    self.parseArgs(argv)
  File "C:\Program Files\Python32\lib\unittest\main.py", line 191, in parseArgs
    self.createTests()
  File "C:\Program Files\Python32\lib\unittest\main.py", line 198, in createTests
    self.module)
  File "C:\Program Files\Python32\lib\unittest\loader.py", line 137, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "C:\Program Files\Python32\lib\unittest\loader.py", line 137, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "C:\Program Files\Python32\lib\unittest\loader.py", line 105, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'schema'

Also while executing test_add_single.py I am getting below error – 

Finding files... done.
Traceback (most recent call last):
  File "D:\rabindra\eclipse\plugins\org.python.pydev_3.9.2.201502050007\pysrc\pydev_runfiles.py", line 468, in __get_module_from_str
    mod = __import__(modname)
  File "C:/Users/rabindra/git/GenSON/test\test_add_single.py", line 24
    schema = {u'type': u'string'}
                    ^
SyntaxError: invalid syntax
ERROR: Module: test_add_single could not be imported (file: C:\Users\rabindra\git\GenSON\test\test_add_single.py).
Importing test modules ... done.

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

I am using attached schema file as well python 3.2.5.

Can someone help me to run for a sample json file and points out what mistakes I am making while execution?

Thanks
Rabindra

**Comment by eliasdorneles** [comment]
@robinnidhi you need Python 3.3 at least.

**Comment by wolverdude** [comment]
It should run on both Python 2 and 3, but I haven't tested it on Windows or using Eclipse, so that might have something to do with it. It's really hard to tell without inspecting your actual environment.

**Comment by eliasdorneles** [comment]
Thing is, Python 3.2.x didn't support the unicode sigil, which appeared only in 3.3:

```
Python 3.2.5 (default, Sep 26 2015, 19:34:17) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> u'test'
  File "<stdin>", line 1
    u'test'
          ^
SyntaxError: invalid syntax
```

AFAIK, most modern code that targets both PY3 and PY2 works only with Python 3.3 onwards.

**Comment by wolverdude** [comment]
Ah, I see. Yes, I only tested it in 2.7 and 3.3. I guess that explains why it took so darn long for people to transition to 3. They made it completely non-backwards compatible.

**Comment by wolverdude** [comment]
There is now a note in the README about compatible Python versions.
