### ISSUE TITLE
TypeError: '<' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by maxandersen** [wolverdude/GenSON#36]
trying to generate schema for a very dynamic format by using 1000's of examples from github and bumping into this exception:

```
Traceback (most recent call last):
  File "genschema.py", line 82, in <module>
    generateschemas()
  File "genschema.py", line 58, in generateschemas
    print(builder.to_json(indent=2))
  File "/Users/max/code/home-assistant/lib/python3.7/site-packages/genson/schema/builder.py", line 82, in to_json
    return json.dumps(self.to_schema(), *args, **kwargs)
  File "/Users/max/code/home-assistant/lib/python3.7/site-packages/genson/schema/builder.py", line 73, in to_schema
    schema.update(self._root_node.to_schema())
  File "/Users/max/code/home-assistant/lib/python3.7/site-packages/genson/schema/node.py", line 62, in to_schema
    generated_schema = schema_generator.to_schema()
  File "/Users/max/code/home-assistant/lib/python3.7/site-packages/genson/schema/generators/object.py", line 80, in to_schema
    self._properties)
  File "/Users/max/code/home-assistant/lib/python3.7/site-packages/genson/schema/generators/object.py", line 91, in _properties_to_schema
    schema_properties[prop] = schema_node.to_schema()
  File "/Users/max/code/home-assistant/lib/python3.7/site-packages/genson/schema/node.py", line 62, in to_schema
    generated_schema = schema_generator.to_schema()
  File "/Users/max/code/home-assistant/lib/python3.7/site-packages/genson/schema/generators/object.py", line 80, in to_schema
    self._properties)
  File "/Users/max/code/home-assistant/lib/python3.7/site-packages/genson/schema/generators/object.py", line 91, in _properties_to_schema
    schema_properties[prop] = schema_node.to_schema()
  File "/Users/max/code/home-assistant/lib/python3.7/site-packages/genson/schema/node.py", line 62, in to_schema
    generated_schema = schema_generator.to_schema()
  File "/Users/max/code/home-assistant/lib/python3.7/site-packages/genson/schema/generators/object.py", line 80, in to_schema
    self._properties)
  File "/Users/max/code/home-assistant/lib/python3.7/site-packages/genson/schema/generators/object.py", line 91, in _properties_to_schema
    schema_properties[prop] = schema_node.to_schema()
  File "/Users/max/code/home-assistant/lib/python3.7/site-packages/genson/schema/node.py", line 62, in to_schema
    generated_schema = schema_generator.to_schema()
  File "/Users/max/code/home-assistant/lib/python3.7/site-packages/genson/schema/generators/object.py", line 80, in to_schema
    self._properties)
  File "/Users/max/code/home-assistant/lib/python3.7/site-packages/genson/schema/generators/object.py", line 91, in _properties_to_schema
    schema_properties[prop] = schema_node.to_schema()
  File "/Users/max/code/home-assistant/lib/python3.7/site-packages/genson/schema/node.py", line 62, in to_schema
    generated_schema = schema_generator.to_schema()
  File "/Users/max/code/home-assistant/lib/python3.7/site-packages/genson/schema/generators/object.py", line 80, in to_schema
    self._properties)
  File "/Users/max/code/home-assistant/lib/python3.7/site-packages/genson/schema/generators/object.py", line 91, in _properties_to_schema
    schema_properties[prop] = schema_node.to_schema()
  File "/Users/max/code/home-assistant/lib/python3.7/site-packages/genson/schema/node.py", line 62, in to_schema
    generated_schema = schema_generator.to_schema()
  File "/Users/max/code/home-assistant/lib/python3.7/site-packages/genson/schema/generators/object.py", line 85, in to_schema
    schema['required'] = sorted(self._required)
TypeError: '<' not supported between instances of 'str' and 'int'
```
I wish I could pinpoint what data files cause the issue but with 1000+ files I haven't yet been able to pinpoint it - but I assume the fix is to somehow keep track on wether types of added values are sortable/comparable.

**Comment by xgodon** [comment]
maybe if you call "to_json" after each merge, you could pinpoint the problem?

**Comment by wolverdude** [comment]
All property names in JSON are strings, so this could only happen if you aren't using valid JSON. Sounds like you found the problem and fixed it though.
