### ISSUE TITLE
Your regex that separates JSON objects is buggy

### ISSUE THREAD

**Issue by ctrlcctrlv** [wolverdude/GenSON#62]
Because JSON strings may well contain `}`.

```python3
fred@mapache:/tmp# jq <Unicode.mediawiki.json|genson
Traceback (most recent call last):
  File "/home/fred/.local/bin/genson", line 8, in <module>
    sys.exit(main())
  File "/home/fred/.local/lib/python3.10/site-packages/genson/cli.py", line 9, in main
    CLI().run()
  File "/home/fred/.local/lib/python3.10/site-packages/genson/cli.py", line 22, in run
    self.add_objects()
  File "/home/fred/.local/lib/python3.10/site-packages/genson/cli.py", line 32, in add_objects
    self._call_with_json_from_fp(self.builder.add_object, fp)
  File "/home/fred/.local/lib/python3.10/site-packages/genson/cli.py", line 125, in _call_with_json_from_fp
    method(json.loads(json_string))
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: "Unterminated string starting at: line 26 column 16 (char 438)"
fred@mapache:/tmp# jq .[] -c <Unicode.mediawiki.json|genson
Traceback (most recent call last):
  File "/home/fred/.local/bin/genson", line 8, in <module>
    sys.exit(main())
  File "/home/fred/.local/lib/python3.10/site-packages/genson/cli.py", line 9, in main
    CLI().run()
  File "/home/fred/.local/lib/python3.10/site-packages/genson/cli.py", line 22, in run
    self.add_objects()
  File "/home/fred/.local/lib/python3.10/site-packages/genson/cli.py", line 32, in add_objects
    self._call_with_json_from_fp(self.builder.add_object, fp)
  File "/home/fred/.local/lib/python3.10/site-packages/genson/cli.py", line 125, in _call_with_json_from_fp
    method(json.loads(json_string))
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: "Unterminated string starting at: line 1 column 230 (char 229)"
```

I needed:

```bash
jq .[] -c < $FILE | genson --delimiter 'newline' | jq
```
Finally yielding:
```json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "revid": {
        "type": "integer"
      },
      "parentid": {
        "type": "integer"
      },
      "minor": {
        "type": "string"
      },
      "user": {
        "type": "string"
      },
      "timestamp": {
        "type": "array",
        "items": {
          "type": "integer"
        }
      },
      "comment": {
        "type": "string"
      },
      "slots": {
        "type": "object",
        "properties": {
          "main": {
            "type": "object",
            "properties": {
              "contentmodel": {
                "type": "string"
              },
              "contentformat": {
                "type": "string"
              },
              "*": {
                "type": "string"
              }
            },
            "required": [
              "*",
              "contentformat",
              "contentmodel"
            ]
          }
        },
        "required": [
          "main"
        ]
      },
      "anon": {
        "type": "string"
      },
      "commenthidden": {
        "type": "string"
      }
    }
  }
}
```

**Comment by wolverdude** [comment]
This is a known issue (#23).

GenSON trying to guess if a file contains multiple JSON objects is a "feature" that probably shouldn't have been added. I'll try to address this in the next release by removing that as the default behavior and requiring the use of a `--delimeter` if multi-object parsing is needed.

**Comment by ctrlcctrlv** [comment]
Sorry

**Comment by wolverdude** [comment]
No need to apologize. Knowing that you also ran into this issue is important. I appreciate the feedback.
